### ISSUE TITLE
maybe a bug!!!

### ISSUE THREAD

**Issue by foralliance** [po0ya/face-magnet#2]
@po0ya  HI
@mahyarnajibi  HI

**face-magnet** is configured according to **readme**. 
When training, point out:
```
Traceback (most recent call last):
  File "./tools/train_net.py", line 30, in <module>
    from datasets.factory import get_imdb
  File "/home/jmx/face-magnet/lib/datasets/factory.py", line 2, in <module>
    from datasets.wider import wider
  File "/home/jmx/face-magnet/lib/datasets/wider.py", line 12, in <module>
    from voc_eval import voc_eval
ImportError: No module named voc_eval
```
**voc_eval** is a test code for voc data sets, so comment it out, like:
```
import uuid
# from voc_eval import voc_eval
from fast_rcnn.config import cfg
```

training again, point out:
```
Traceback (most recent call last):
  File "./tools/train_net.py", line 30, in <module>
    from datasets.factory import get_imdb
  File "/home/jmx/face-magnet/lib/datasets/factory.py", line 3, in <module>
    from datasets.csvdb import csvdb
ImportError: No module named csvdb
```
What is **csvdb**?  In **lib/datasets folder**, there is no such code.

**Comment by po0ya** [comment]
Hi @foralliance 
Thanks for pointing these out. It's nothing to be worried about as a major bug. csvdb was something that we developed internally to read the datasets from csv files.
I updated these points, please let us know if you find more.

**Comment by foralliance** [comment]
@po0ya HI
thanks your reply

I have another questions:
1. There are three corresponding `xxxx_multi layers` under the **RPN folder**. In the `prototxt file` of the **models/wider/VGG16/train**, you don't use these layers. by analyzing the code, i think the three layers should correspond to the case of **IMS_PER_BATCH >1**.   right?

Take `facemagnet.prototxt` for example,  I replaced the `AnchorTargetLayer`, `ProposalLayer`, `ProposalTargetLayer`, with the corresponding `xxx_multi layer`,and then modified `IMS_PER_BATCH=2`. 
I found that the code could also be trained properly. **Does this indicate that the code in this article supports IMS_PER_BATCH>1?** In py-faster-rcnn, it seems that only `IMS_PER_BATCH=1` is supported.
that's my understanding, I'm not sure it is right.

2. Can you provide **a trained model** for debugging test code.

hope for your reply

**Comment by foralliance** [comment]
@po0ya HI
Another two questions:

1. There are `three corresponding xxxx_multi layers` under the RPN folder. In the prototxt file of the models/wider/VGG16/train folder, you don't use these layers. 
By analyzing the code, **i think the three layers should correspond to the case of IMS_PER_BATCH >1**. **right???**

Take `facemagnet.prototxt` for example, I replaced the `AnchorTargetLayer`, `ProposalLayer`, `ProposalTargetLayer`, with the `corresponding xxx_multi layer`, then modified `IMS_PER_BATCH=2`.
I found that the code could also be trained properly. 
**Does this indicate that the code in this article supports IMS_PER_BATCH>1?** .In py-faster-rcnn, it seems that only IMS_PER_BATCH=1 is supported.

that's my understanding, I'm not sure it is right.

2. Can you provide **a trained model** for debugging test code.

Hope for your reply!!

**Comment by foralliance** [comment]
@po0ya HI
Another two questions:

1. 
There are `three corresponding xxxx_multi layers` under the RPN folder. In the prototxt file of the models/wider/VGG16/train folder, you don't use these layers. 
By analyzing the code, **i think the three layers should correspond to the case of IMS_PER_BATCH >1**. **right???**

Take `facemagnet.prototxt` for example, I replaced the `AnchorTargetLayer`, `ProposalLayer`, `ProposalTargetLayer`, with the `corresponding xxx_multi layer`, then modified `IMS_PER_BATCH=2`.
I found that the code could also be trained properly. 
**Does this indicate that the code in this article supports IMS_PER_BATCH>1?** .In py-faster-rcnn, it seems that only IMS_PER_BATCH=1 is supported.

that's my understanding, I'm not sure it is right.

2. 
Can you provide **a trained model** for debugging test code.

**Comment by po0ya** [comment]
Hey,

Yes these layers allow multi images per batch, these are tested. 
Providing a trained model is on my schedule, but I’m super busy with other things now unfortunately.

**Comment by foralliance** [comment]
@po0ya  HI
In `skipface.prototxt`, in the **RPN NORM section**, the Deconvolution layer's output dimension is **1**. 
Is there any advantage in using settings where the output dimension is 1?

**Comment by foralliance** [comment]
@po0ya HI
**Another three questions:**

1. 
In `skipface.prototxt(train)`, in **RPN NORM section**, the Deconvolution layer's output dimension is **1**.
**Is there any advantage in using settings where the output dimension is 1????**

2.
For **PASCAL Faces** detection, can you provide the relevant **pascal_imglist.csv file**????

3.
The test results of **FDDB data** are all rectangular boxes, like:
`195 62 128 204 0.966717064381 `
but it seems the ellipse box(`58.984614 39.593000 -1.345725 115.094800 81.162477  1`) is required when the official test is provided. **how to transfer the rectangle box to ellipse box???**

**Another two little problems:**

1.
In readme, in the [Single image detection](https://github.com/po0ya/face-magnet#single-image-detection) section, the example you gave is

`. / experiments/scripts/test_single.sh facemagnet data/demo/demo0.jpg --pyramid`

I think we should add a parameter **max_size**, that is

`. / experiments/scripts/test_single.sh facemagnet data/demo/demo0.jpg --max_size 3000 --pyramid`

Because the original `cfg.TEST.MAX_SIZE = 1500` was too small to to reflect the pyramid advantage, especially when scale is equal to 2

2.
When testing the **FDDB dataset**, according parameters:` args.single=False`, `imdb='fddb'`, an **error** is reported when output_dir is obtained．

```
Traceback (most recent call last):
  File "./tools/test_net.py", line 171, in <module>
    output_dir = get_output_dir(imdb, postfix=postfix)
  File "/home/jmx/face-magnet/tools/../lib/fast_rcnn/config.py", line 236, in get_output_dir
    outdir = osp.abspath(osp.join(__C.ROOT_DIR, 'output', __C.EXP_DIR, imdb.name))
AttributeError: 'str' object has no attribute 'name'
```

However, this error does not affect the final test
